### ISSUE TITLE
プラン登録押しても何も起きない

### ISSUE THREAD

**Issue by deerboy** [moriyamasaaaki/jobApp#236]
![image](https://user-images.githubusercontent.com/5842851/77307197-2e459980-6d3c-11ea-93ae-0a1ada9a08b2.png)

たぶ多分自分が無料プランだからだと思うのですが、その場合押せないようにするか、自分が無料プランである旨をわかるようにして欲しい

**Comment by moriyamasaaaki** [comment]
### 修正内容
- 有料プラン登録時、無料プランのdisabled解除、ダイアログ追加
- ダイアログの文言変更

### 修正の挙動

<img width="1024" alt="スクリーンショット 2020-03-25 13 06 32" src="https://user-images.githubusercontent.com/49673112/77501899-adea7a00-6e9c-11ea-9e3c-7647a3bbded0.png">

- 有料プラン登録時はどちらのボタンを押しても無料プランに戻れるダイアログ追加しました。
<img width="546" alt="スクリーンショット 2020-03-25 13 06 37" src="https://user-images.githubusercontent.com/49673112/77501912-b2af2e00-6e9c-11ea-88f1-eec08dce4318.png">

ご確認よろしくお願い致します。
