### ISSUE TITLE
refactor: トップの共通パーツを統一する

### ISSUE THREAD

**Issue by deerboy** [moriyamasaaaki/jobApp#58]
![image](https://user-images.githubusercontent.com/5842851/71140542-e56dd880-2254-11ea-974e-e7d44258e416.png)

見出しやボックスが全く同じなのに別class管理なのが無駄なので統一する。

**Comment by deerboy** [comment]
.attencion と .new でほぼ同じCSS書いてるのが無駄なので

.box や
.hdg（見出し）

を独立したブロックとしてCSS定義して再利用すべし

**Comment by moriyamasaaaki** [comment]
共通部分は一つのCSSにまとめてそこから.new.attentionにインポートするってことですね！
お気に入りページと求人一覧ページに関しては全く同じくらいのレベルなのでそこもまとめる必要ありですね。

**Comment by deerboy** [comment]
いや、インポートではなく

.hdg
.box 

というクラスを作るという意味です。

**Comment by moriyamasaaaki** [comment]
共通クラスを作るってことですね。

**Comment by deerboy** [comment]
https://to.camp/lesson?v=rPzwtL7kYmAZmRADPx9s
